# vim: ts=2:sw=2:tw=80:nowrap
"""
Interface to comedi user library using ctypes.

This provides an interface that is nearly identical to the c-library interface.
There are several advantages to this as opposed to using a SWIG interface:
1) The interface is not opaque--for functions, one can easily see what types
  arguments are required and what type of return values are given.
2) One can directly read the typical documentation sources for comedi, including
  the unix man pages and the pdf-generated manual.
3) One does not need to learn arcane interfaces generated by swig that are not
  well (or at all) documented and, in many cases, divergent from the given
  c-library interface.
4) ctypes is a very well documented package for interfacing Python to
  c-libraries.
5) ctypes comes standard with Python
"""

from ctypesgen_comedi import *
